backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/event/index.md"
        label: "Event"
        name: "event"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "EventHosts"
            name: "eventHosts"
            widget: "list"
            fields:
              - {label: "Year", name: "year", widget: "string"}
              - {label: "Host", name: "host", widget: "string"}
          - {label: "Location Address Lines",
             name: "locationAddressLines",
             widget: "list",
             field: {label: "Line", name: "line", widget: "string"}}
          - {label: "Location Link", name: "gMapsLocationEmbedLink", widget: "string"}
      - file: "src/pages/schedule/index.md"
        label: "Schedule"
        name: "schedule"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Daty", name: "day", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Schedule Height", name: "scheduleHeight", widget: "number"}
          - label: "Schedule Theme"
            name: "scheduleTheme"
            widget: "list"
            fields:
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Color", name: "color", widget: "string"}
          - label: "Schedule Data"
            name: "scheduleData"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Location", name: "location", widget: "string"}
              - {label: "Start Time", name: "startTime", widget: "number"}
              - {label: "Duration", name: "duration", widget: "number"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
      - file: "src/pages/register/index.md"
        label: "Register Page"
        name: "register"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Register Link", name: "registerLink", widget: "string"}
